name: writernote
version: 0.1.7

summary: Writernote

description: |
  writernote is a multiplatform application that allows you to take notes by recording audio, 
  translate it later into text, and listen to it in an intelligent way.

grade: stable
#confinement: classic
confinement: strict
base: core20

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  writernote:
    command-chain: ["snap/command-chain/alsa-launch"]
    command: bin/desktop-launch $SNAP/bin/writernote
    #$SNAP/snap/command-chain/alsa-launch
    # enviroment for core20
    environment:
    #  #LD_LIBRARY_PATH: $SNAP/lib/python3.8/site-packages
      PYTHONPATH: $SNAP/lib/python3.8/site-packages:$SNAP/usr/lib/python3/dist-packages
      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa/alsa.conf
    
    plugs:
      #- alsa
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - audio-record
      - home
      - pulseaudio
      - unity7
      - browser-support
      - network
      - gsettings
      - network-bind
      - audio-playback
      - network-manager
      #- process-control
      #- mount-observe

      #- optical-drive
      #- removable-media
      #- screen-inhibit-control
  
    slots:
      - mpris


layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

  #/usr/share/X11:
  #  bind: $SNAP/usr/share/X11

plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  qt551:
    interface: content
    target: $SNAP/qt551
    default-provider: qt551


parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins


  writernote:
    after: [desktop-qt5, alsa-mixin]
    plugin: python
    source: .

    # setting enviroment for python3 for the gcc [Python.h]
    build-environment:
      - C_INCLUDE_PATH: /usr/include/python3.8/

    build-packages:
      #- ffmpeg
      #for qt
      - libxcb-xinerama0-dev
      - qt5-default
      #- ^libxcb.*-dev
      - libx11-xcb-dev 
      - libglu1-mesa-dev 
      - libxrender-dev 
      - libxi-dev 
      - libxkbcommon-dev 
      - libxkbcommon-x11-dev

      - libxcursor-dev 
      - libxcomposite-dev 
      - libxdamage-dev 
      - libxrandr-dev 
      - libxtst-dev 
      - libxss-dev 
      - libdbus-1-dev 
      - libevent-dev 
      - libfontconfig1-dev 
      - libcap-dev  
      - libudev-dev 
      - libpci-dev 
      - libnss3-dev  
      - libegl1-mesa-dev 
      - gperf 
      - bison 
      - nodejs

      #qmediaplayer
      - libgstreamer1.0-dev 
      - libgstreamer-plugins-base1.0-dev 
      - libgstreamer-plugins-good1.0-dev 
      - libgstreamer-plugins-bad1.0-dev


      - build-essential
      - python3
      - python3.8-dev
      - python3-dev
      - python3-pyqt5
      - libpython3-dev
      - python3-setuptools
      - execstack
      - libasound2-dev
      - gcc
      - libopus-dev
      - python3-pip
      - python3-wheel
      - python3-venv
      - python3-minimal
      - python3-pkg-resources
      - python3.8-minimal
      - libpython3-stdlib
      - libpython3.8-stdlib
      # tg
      - qtbase5-private-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - liblzma-dev
      - libpulse-dev
      - libqt5svg5-dev
      - libqt5waylandclient5-dev
      - libssl-dev
      - libxcb1-dev
      - libxcb-screensaver0-dev
      - zlib1g-dev


    stage-packages:
      #gstramer
      - libgstreamer1.0-0 
      - gstreamer1.0-plugins-base 
      - gstreamer1.0-plugins-good 
      - gstreamer1.0-plugins-bad 
      - gstreamer1.0-plugins-ugly 
      - gstreamer1.0-libav 
      - gstreamer1.0-doc 
      - gstreamer1.0-tools 
      - gstreamer1.0-x 
      - gstreamer1.0-alsa 
      - gstreamer1.0-gl 
      - gstreamer1.0-gtk3 
      - gstreamer1.0-qt5 
      - gstreamer1.0-pulseaudio
      
      ##qmultimedia
      ##for qt
      - libxcb-xinerama0-dev
      - qt5-default
      - libx11-xcb-dev 
      - libglu1-mesa-dev 
      - libxrender-dev 
      - libxi-dev 
      - libxkbcommon-dev 
      - libxkbcommon-x11-dev

      - libxcursor-dev 
      - libxcomposite-dev 
      - libxdamage-dev 
      - libxrandr-dev 
      - libxtst-dev 
      - libxss-dev 
      - libdbus-1-dev 
      - libevent-dev 
      - libfontconfig1-dev 
      - libcap-dev  
      - libudev-dev 
      - libpci-dev 
      - libnss3-dev  
      - libegl1-mesa-dev 
      - gperf 
      - bison 
      - nodejs

      - libgstreamer1.0-dev 
      - libgstreamer-plugins-base1.0-dev 
      - libgstreamer-plugins-good1.0-dev 
      - libgstreamer-plugins-bad1.0-dev

      #tg
      - qt5-image-formats-plugins
      - qtwayland5
      - libgtk-3-0
      - liblzma5
      - libopus0
      - libpulse0
      - libpulse-dev
      - libqt5svg5
      - libqt5waylandclient5
      - libssl1.1
      - libxcb1
      - libxcb-screensaver0
      - zlib1g

      # alsa for qt
      - libasound2-dev 
      #- pulseaudio

      # implementation for core20
      - libpython3-stdlib
      - libpython3.8-stdlib
      - libpython3.8-minimal
      - python3-pip
      - python3-wheel
      - python3-setuptools
      - python3-venv
      - python3-minimal
      - python3-pkg-resources
      - python3.8-minimal

      - python3
      #- libc-bin
      #- locales
      - libasound2
      - python3-pyqt5
      - python3-tk
      - python3-pyaudio
      #- python-pyaudio # not available on core20, in core 18 yes
      - qt5-gtk-platformtheme
      - python3-pyqt5.qtwebengine
      - python3-apt
      - python3-pyqt5.qtmultimedia
      - python3-distutils     
      - ffmpeg
      #- try: python3-nanomsg #not available on core20, in core 18 yes
      #- libmpfr6
      #- libgmp10
      - libqt5multimedia5-plugins

      - libcanberra-gtk-module 
      - libcanberra-gtk3-module
      - libasound2-plugins
      # audio
      #- libasound0
      #- libortop9
    
    python-packages:
      - setuptools #>=45.2.0
      - wheel
      - pydub
      - SpeechRecognition
      - psutil #>=5.7.2
      - googletrans
      - nvpy
      - Wave
      - pytesseract
      
  
  qt5-xdgdesktopportal-platform:
    plugin: nil
    stage-packages:
      - qt5-xdgdesktopportal-platformtheme

  # Qt checks that ibus-daemon binary is present, otherwise doesn't work
  ibus:
    plugin: nil
    stage-packages:
      - ibus

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  